version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: komikcast-api
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    tty: true

volumes:
  redis_data: