version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: komikcast-api
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    tty: true